version: "3.9"

services:
  webapp:
    build:
      context: ./src/Mortgage.UI/
      dockerfile: Dockerfile
    ports:
      - "3000:80"
  api:
    build:
      context: ./src
      dockerfile: Mortgage.Api/Dockerfile
    ports:
      - "5000:80"
