version: "3.9"

services:
  webapp:
    build:
      context: ./src/mortgage.amortization.ui/
      dockerfile: Dockerfile
    ports:
      - "3000:80"
  api:
    build:
      context: ./src
      dockerfile: mortgage.amortization.api/Dockerfile
    ports:
      - "5000:80"
